"""P3 controlled knowledge-evolution evidence and persistence contracts."""

from .applicability import (
    ApplicabilityEnvironment,
    ApplicabilityReason,
    ApplicabilityStatus,
    KnowledgeApplicabilityResult,
    evaluate_applicability,
)
from .canonicalize import (
    CanonicalProposal,
    KnowledgeProposal,
    ProposalRejectionReason,
    ProposalValidation,
    UnsafeKnowledgeContentError,
    validate_and_canonicalize,
)
from .eligibility import (
    SUPPORTED_POLICY,
    CandidateEligibilityInput,
    CandidateEligibilityResult,
    EligibilityReason,
    EligibilityStatus,
    evaluate_candidate_eligibility,
)
from .extraction import (
    CandidateExtractionOutcome,
    ExtractionFailureReason,
    ExtractionStatus,
    KnowledgeExtractionContext,
    KnowledgeExtractionRequest,
    KnowledgeExtractionResult,
    KnowledgeExtractor,
    RejectedProposal,
    build_extraction_context,
    extract_candidates,
)
from .index import CandidateComparison, CandidateIndex, CandidateRelation
from .lifecycle import (
    LEGAL_TRANSITIONS,
    KnowledgeLifecycleManager,
    KnowledgeLifecycleTransition,
    LifecycleActorType,
    LifecycleProjection,
    LifecycleReason,
    LifecycleState,
)
from .materialize import (
    KnowledgeMaterializationResult,
    MaterializationStatus,
    materialize_candidate,
    materialized_skill_root,
)
from .retrieval import (
    KnowledgeRetrievalReceipt,
    KnowledgeRetriever,
    RetrievedKnowledge,
    SuppressionReason,
)
from .review import (
    KnowledgeReviewReceipt,
    ReviewDecision,
    ReviewerType,
    create_review,
)
from .scope import (
    RepositoryIdentityMethod,
    RepositoryScopeIdentity,
    RepositoryScopeReason,
    RepositoryScopeResolution,
    RepositoryScopeResolver,
    RepositoryScopeStatus,
    normalize_git_remote,
    normalize_project_key,
)
from .store import (
    ImmutableWriteStatus,
    KnowledgeRecordStore,
    KnowledgeStoreError,
)
from .task_success import (
    TaskSuccessEvidence,
    TaskSuccessSource,
    TaskSuccessStatus,
)
from .types import (
    CandidateType,
    ContentClass,
    KnowledgeCandidate,
    SourceTurnReference,
)
from .usage import (
    KnowledgeUsageMode,
    KnowledgeUsageOutcomeAssociation,
    KnowledgeUsageReceipt,
    associate_usage_outcome,
    persist_usage,
)
from .validation import (
    CandidateValidationResult,
    ValidationReason,
    ValidationStatus,
    validate_candidate,
)

__all__ = [
    "SUPPORTED_POLICY",
    "ApplicabilityEnvironment",
    "ApplicabilityReason",
    "ApplicabilityStatus",
    "CandidateEligibilityInput",
    "CandidateEligibilityResult",
    "CandidateExtractionOutcome",
    "CandidateComparison",
    "CandidateIndex",
    "CandidateRelation",
    "CandidateType",
    "CandidateValidationResult",
    "CanonicalProposal",
    "ContentClass",
    "EligibilityReason",
    "EligibilityStatus",
    "ExtractionFailureReason",
    "ExtractionStatus",
    "ImmutableWriteStatus",
    "KnowledgeCandidate",
    "KnowledgeApplicabilityResult",
    "KnowledgeExtractionContext",
    "KnowledgeExtractionRequest",
    "KnowledgeExtractionResult",
    "KnowledgeExtractor",
    "KnowledgeLifecycleManager",
    "KnowledgeLifecycleTransition",
    "KnowledgeMaterializationResult",
    "KnowledgeProposal",
    "KnowledgeRecordStore",
    "KnowledgeRetrievalReceipt",
    "KnowledgeRetriever",
    "KnowledgeReviewReceipt",
    "KnowledgeStoreError",
    "KnowledgeUsageMode",
    "KnowledgeUsageOutcomeAssociation",
    "KnowledgeUsageReceipt",
    "LEGAL_TRANSITIONS",
    "LifecycleActorType",
    "LifecycleProjection",
    "LifecycleReason",
    "LifecycleState",
    "MaterializationStatus",
    "RepositoryIdentityMethod",
    "RepositoryScopeIdentity",
    "RepositoryScopeReason",
    "RepositoryScopeResolution",
    "RepositoryScopeResolver",
    "RepositoryScopeStatus",
    "ReviewDecision",
    "ReviewerType",
    "RetrievedKnowledge",
    "ProposalRejectionReason",
    "ProposalValidation",
    "RejectedProposal",
    "SourceTurnReference",
    "TaskSuccessEvidence",
    "TaskSuccessSource",
    "TaskSuccessStatus",
    "SuppressionReason",
    "UnsafeKnowledgeContentError",
    "ValidationReason",
    "ValidationStatus",
    "build_extraction_context",
    "associate_usage_outcome",
    "create_review",
    "evaluate_candidate_eligibility",
    "evaluate_applicability",
    "extract_candidates",
    "materialize_candidate",
    "materialized_skill_root",
    "normalize_git_remote",
    "normalize_project_key",
    "persist_usage",
    "validate_and_canonicalize",
    "validate_candidate",
]
